blank_issues_enabled: false
contact_links:
  - name: "Discussions 讨论"
    url: https://github.com/Seeed-Studio/Smarter-Spaces-Solutions/discussions
    about: "Idea not fully formed yet? Start here / 想法还不成形？先来这里聊聊"
